### ISSUE TITLE
Question:  When will mongo v6 be supported?

### ISSUE THREAD

**Issue by willoughby** [kobil-systems/mongodb#381]
We're looking into Elixir but our infrastructure uses Mongo V6. Unfortunately I've been unable to use this library due to the following error

```  ** (Mongo.Error) OP_QUERY is no longer supported. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal 5739101
            (mongodb 1.0.0) lib/mongo/cursor.ex:56: anonymous fn/6 in Enumerable.Mongo.Cursor.start_fun/6
            (elixir 1.15.5) lib/stream.ex:1612: anonymous fn/5 in Stream.resource/3
            (elixir 1.15.5) lib/enum.ex:4387: Enum.reverse/1
            (elixir 1.15.5) lib/enum.ex:3702: Enum.to_list/1```

**Comment by scottmessinger** [comment]
Great question! We’d love to work on that, but no plans. We’d welcome the help!

**Comment by prabello** [comment]
> Great question! We’d love to work on that, but no plans. We’d welcome the help!

@scottmessinger is there any point where one could start to understand what is needed to help on this?

**Comment by scottmessinger** [comment]
Hi Pedro,

My current hope is we can migrate the community to the zookzook elixir
library (https://github.com/zookzook/elixir-mongodb-driver). That would
require migrating the ecto adapter and having an upgrade guide.

Let me know if you're interested in helping!

**Comment by bugsxxx** [comment]
Hello Scott
Also trying to upgrade mongo version to v6, and just saw this issue from September... any news here any prediction?

Thanks for this great lib.

**Comment by scottmessinger** [comment]
@bugsxxx Sorry for the lack of updates! My plan is to deprecate this library and move the community over to the (more popular) https://github.com/zookzook/elixir-mongodb-driver To do that, I need to create a formal upgrade guide and post it. Here's an initial start on the work:

https://github.com/elixir-mongo/mongodb_ecto/pull/190#issuecomment-1941684011

Currently, I'm thinking it might be this summer.

**Comment by bugsxxx** [comment]
Thanks Scott!

I will probably have to change the driver for the zookzook one, DBA team is pushing for the upgrade I don't have till summer unfortunately.
I will take a look on the initial work.

**Comment by scottmessinger** [comment]
@bugsxxx Either way, you'll need to change the driver to the zookzook one -- the plan is this driver gets deprecated in favor of the zookzook one. If you make the transition, I would LOVE if you could post any thoughts/observations/changes needed to make the transition!

Are you all using the ecto adapter as well?

**Comment by bugsxxx** [comment]
Hello Scott
I will have to make the transition, as soon as possible, not yet scheduled, I will post any thoughts that may have relevance.
Thanks, see you soon.
